### ISSUE TITLE
Error in 2 player match BO1, 301 while finalizing match

### ISSUE THREAD

**Issue by Chmieloo** [thordy/cakeapp#20]
TypeError: /home/hops/Projects/cakeapp/views/leg_result.pug:165
    163|                             p= player.name
    164|                         td
  > 165|                             p= statistics.darts_thrown
    166|                         td
    167|                             p= statistics.first_nine_ppd.toFixed(2)
    168|                         td

Cannot read property 'darts_thrown' of undefined
    at eval (eval at wrap (/home/hops/Projects/cakeapp/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:792:67)
    at eval (eval at wrap (/home/hops/Projects/cakeapp/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:841:4)
    at template (eval at wrap (/home/hops/Projects/cakeapp/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:3065:202)
    at Object.exports.renderFile (/home/hops/Projects/cakeapp/node_modules/pug/lib/index.js:428:38)
    at Object.exports.renderFile (/home/hops/Projects/cakeapp/node_modules/pug/lib/index.js:418:21)
    at View.exports.__express [as engine] (/home/hops/Projects/cakeapp/node_modules/pug/lib/index.js:465:11)
    at View.render (/home/hops/Projects/cakeapp/node_modules/express/lib/view.js:128:8)
    at tryRender (/home/hops/Projects/cakeapp/node_modules/express/lib/application.js:640:10)
    at EventEmitter.render (/home/hops/Projects/cakeapp/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/home/hops/Projects/cakeapp/node_modules/express/lib/response.js:971:7)
    at /home/hops/Projects/cakeapp/controller/match_controller.js:254:9
    at tryCatcher (/home/hops/Projects/cakeapp/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.module.exports.Promise._settlePromiseFromHandler (/home/hops/Projects/cakeapp/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise.module.exports.Promise._settlePromise (/home/hops/Projects/cakeapp/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise.module.exports.Promise._settlePromise0 (/home/hops/Projects/cakeapp/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise.module.exports.Promise._settlePromises (/home/hops/Projects/cakeapp/node_modules/bluebird/js/release/promise.js:693:18)

**Comment by Chmieloo** [comment]
This happens probably because I simulated 6 darter. Still, should be handled.
